language: node_js
node_js:
  - 18
branches:
  only:
    - main
cache:
  yarn: true
script:
  - git config --global user.name "Nevermorexu"
  - git config --global user.email "sunsboyxu@sina.com"
  - echo "machine github.com login Nevermorexu password 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" > ~/.netrc
  - yarn install
  - GIT_USER="Nevermorexu" yarn deploy
