language: node_js
node_js:
  - 16
branches:
  only:
    - main
cache:
  yarn: true
script:
  - git config --global user.name "Nevermorexu"
  - git config --global user.email "sunsboyxu@sina.com"
  - echo "machine github.com login Nevermorexu password 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" > ~/.netrc
  - yarn install
  - GIT_USER="Nevermorexu" yarn deploy
